# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-19 10:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edc_lab', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalmanifest',
            name='manifest_identifier',
            field=models.CharField(db_index=True, default='20170219104627508648', max_length=25, verbose_name='Manifest Identifier'),
        ),
        migrations.AlterField(
            model_name='manifest',
            name='manifest_identifier',
            field=models.CharField(default='20170219104627508648', max_length=25, unique=True, verbose_name='Manifest Identifier'),
        ),
    ]
