# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-19 12:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edc_lab', '0004_auto_20170219_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='aliquot',
            name='requisition_identifier',
            field=models.CharField(editable=False, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='aliquot',
            name='slug',
            field=models.CharField(db_index=True, editable=False, help_text='a field used for quick search', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='historicalaliquot',
            name='requisition_identifier',
            field=models.CharField(editable=False, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='historicalaliquot',
            name='slug',
            field=models.CharField(db_index=True, editable=False, help_text='a field used for quick search', max_length=250, null=True),
        ),
    ]
