# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-19 14:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edc_lab', '0005_auto_20170219_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmanifest',
            name='slug',
            field=models.CharField(db_index=True, editable=False, help_text='a field used for quick search', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='manifest',
            name='slug',
            field=models.CharField(db_index=True, editable=False, help_text='a field used for quick search', max_length=250, null=True),
        ),
    ]
