# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-19 17:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edc_lab', '0006_auto_20170219_1620'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manifest',
            options={'ordering': ('-manifest_identifier',)},
        ),
        migrations.AddField(
            model_name='historicalmanifest',
            name='comment',
            field=models.TextField(null=True, verbose_name='Comment'),
        ),
        migrations.AddField(
            model_name='historicalmanifest',
            name='shipped',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='manifest',
            name='comment',
            field=models.TextField(null=True, verbose_name='Comment'),
        ),
        migrations.AddField(
            model_name='manifest',
            name='shipped',
            field=models.BooleanField(default=False),
        ),
    ]
