# -*- coding: utf-8 -*-
from south.utils import datetime_utils as datetime
from south.db import db
from south.v2 import SchemaMigration
from django.db import models


class Migration(SchemaMigration):

    def forwards(self, orm):
        # Adding model 'ReferenceRangeList'
        db.create_table(u'lab_clinic_reference_referencerangelist', (
            (u'id', self.gf('django.db.models.fields.AutoField')(primary_key=True)),
            ('created', self.gf('django.db.models.fields.DateTimeField')(default=datetime.datetime.now, blank=True)),
            ('modified', self.gf('django.db.models.fields.DateTimeField')(default=datetime.datetime.now, blank=True)),
            ('user_created', self.gf('django.db.models.fields.CharField')(default='', max_length=250, db_index=True)),
            ('user_modified', self.gf('django.db.models.fields.CharField')(default='', max_length=250, db_index=True)),
            ('hostname_created', self.gf('django.db.models.fields.CharField')(default='mac.local', max_length=50, db_index=True, blank=True)),
            ('hostname_modified', self.gf('django.db.models.fields.CharField')(default='mac.local', max_length=50, db_index=True, blank=True)),
            ('name', self.gf('django.db.models.fields.CharField')(max_length=50)),
            ('description', self.gf('django.db.models.fields.CharField')(max_length=250, null=True, blank=True)),
            ('list_date', self.gf('django.db.models.fields.DateField')(null=True, blank=True)),
        ))
        db.send_create_signal('lab_clinic_reference', ['ReferenceRangeList'])

        # Adding model 'ReferenceRangeListItemAudit'
        db.create_table(u'lab_clinic_reference_referencerangelistitem_audit', (
            ('created', self.gf('django.db.models.fields.DateTimeField')(default=datetime.datetime.now, blank=True)),
            ('modified', self.gf('django.db.models.fields.DateTimeField')(default=datetime.datetime.now, blank=True)),
            ('user_created', self.gf('django.db.models.fields.CharField')(default='', max_length=250, db_index=True)),
            ('user_modified', self.gf('django.db.models.fields.CharField')(default='', max_length=250, db_index=True)),
            ('hostname_created', self.gf('django.db.models.fields.CharField')(default='mac.local', max_length=50, db_index=True, blank=True)),
            ('hostname_modified', self.gf('django.db.models.fields.CharField')(default='mac.local', max_length=50, db_index=True, blank=True)),
            ('_audit_subject_identifier', self.gf('django.db.models.fields.CharField')(max_length=50, null=True)),
            ('code', self.gf('django.db.models.fields.CharField')(max_length=25, null=True, blank=True)),
            ('scale', self.gf('django.db.models.fields.CharField')(default='increasing', max_length=25)),
            ('gender', self.gf('django.db.models.fields.CharField')(max_length=10)),
            ('hiv_status', self.gf('django.db.models.fields.CharField')(default='ANY', max_length=10)),
            ('value_unit', self.gf('django.db.models.fields.CharField')(max_length=10, null=True)),
            ('value_low', self.gf('django.db.models.fields.DecimalField')(null=True, max_digits=12, decimal_places=4, blank=True)),
            ('value_low_quantifier', self.gf('django.db.models.fields.CharField')(default='>=', max_length=10)),
            ('value_high', self.gf('django.db.models.fields.DecimalField')(null=True, max_digits=12, decimal_places=4, blank=True)),
            ('value_high_quantifier', self.gf('django.db.models.fields.CharField')(default='<=', max_length=10)),
            ('age_low', self.gf('django.db.models.fields.IntegerField')(default=0, null=True, blank=True)),
            ('age_low_unit', self.gf('django.db.models.fields.CharField')(default='D', max_length=10, blank=True)),
            ('age_low_quantifier', self.gf('django.db.models.fields.CharField')(default='>=', max_length=10, blank=True)),
            ('age_high', self.gf('django.db.models.fields.IntegerField')(default=99999, null=True, blank=True)),
            ('age_high_unit', self.gf('django.db.models.fields.CharField')(default='Y', max_length=10, blank=True)),
            ('age_high_quantifier', self.gf('django.db.models.fields.CharField')(default='<=', max_length=10, blank=True)),
            ('panic_value_low', self.gf('django.db.models.fields.DecimalField')(null=True, max_digits=12, decimal_places=4, blank=True)),
            ('panic_value_high', self.gf('django.db.models.fields.DecimalField')(null=True, max_digits=12, decimal_places=4, blank=True)),
            ('active', self.gf('django.db.models.fields.BooleanField')(default=True)),
            ('dummy', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('comment', self.gf('django.db.models.fields.CharField')(max_length=250, blank=True)),
            ('import_datetime', self.gf('django.db.models.fields.DateTimeField')(null=True, blank=True)),
            ('test_code', self.gf('django.db.models.fields.related.ForeignKey')(related_name='_audit_referencerangelistitem', to=orm['lab_clinic_api.TestCode'])),
            ('reference_range_list', self.gf('django.db.models.fields.related.ForeignKey')(related_name='_audit_referencerangelistitem', to=orm['lab_clinic_reference.ReferenceRangeList'])),
            ('_audit_timestamp', self.gf('django.db.models.fields.DateTimeField')(auto_now_add=True, db_index=True, blank=True)),
            ('_audit_change_type', self.gf('django.db.models.fields.CharField')(max_length=1)),
            (u'id', self.gf('django.db.models.fields.IntegerField')(db_index=True)),
            ('_audit_id', self.gf('django.db.models.fields.AutoField')(primary_key=True)),
        ))
        db.send_create_signal('lab_clinic_reference', ['ReferenceRangeListItemAudit'])

        # Adding model 'ReferenceRangeListItem'
        db.create_table(u'lab_clinic_reference_referencerangelistitem', (
            (u'id', self.gf('django.db.models.fields.AutoField')(primary_key=True)),
            ('created', self.gf('django.db.models.fields.DateTimeField')(default=datetime.datetime.now, blank=True)),
            ('modified', self.gf('django.db.models.fields.DateTimeField')(default=datetime.datetime.now, blank=True)),
            ('user_created', self.gf('django.db.models.fields.CharField')(default='', max_length=250, db_index=True)),
            ('user_modified', self.gf('django.db.models.fields.CharField')(default='', max_length=250, db_index=True)),
            ('hostname_created', self.gf('django.db.models.fields.CharField')(default='mac.local', max_length=50, db_index=True, blank=True)),
            ('hostname_modified', self.gf('django.db.models.fields.CharField')(default='mac.local', max_length=50, db_index=True, blank=True)),
            ('code', self.gf('django.db.models.fields.CharField')(max_length=25, null=True, blank=True)),
            ('scale', self.gf('django.db.models.fields.CharField')(default='increasing', max_length=25)),
            ('gender', self.gf('django.db.models.fields.CharField')(max_length=10)),
            ('hiv_status', self.gf('django.db.models.fields.CharField')(default='ANY', max_length=10)),
            ('value_unit', self.gf('django.db.models.fields.CharField')(max_length=10, null=True)),
            ('value_low', self.gf('django.db.models.fields.DecimalField')(null=True, max_digits=12, decimal_places=4, blank=True)),
            ('value_low_quantifier', self.gf('django.db.models.fields.CharField')(default='>=', max_length=10)),
            ('value_high', self.gf('django.db.models.fields.DecimalField')(null=True, max_digits=12, decimal_places=4, blank=True)),
            ('value_high_quantifier', self.gf('django.db.models.fields.CharField')(default='<=', max_length=10)),
            ('age_low', self.gf('django.db.models.fields.IntegerField')(default=0, null=True, blank=True)),
            ('age_low_unit', self.gf('django.db.models.fields.CharField')(default='D', max_length=10, blank=True)),
            ('age_low_quantifier', self.gf('django.db.models.fields.CharField')(default='>=', max_length=10, blank=True)),
            ('age_high', self.gf('django.db.models.fields.IntegerField')(default=99999, null=True, blank=True)),
            ('age_high_unit', self.gf('django.db.models.fields.CharField')(default='Y', max_length=10, blank=True)),
            ('age_high_quantifier', self.gf('django.db.models.fields.CharField')(default='<=', max_length=10, blank=True)),
            ('panic_value_low', self.gf('django.db.models.fields.DecimalField')(null=True, max_digits=12, decimal_places=4, blank=True)),
            ('panic_value_high', self.gf('django.db.models.fields.DecimalField')(null=True, max_digits=12, decimal_places=4, blank=True)),
            ('active', self.gf('django.db.models.fields.BooleanField')(default=True)),
            ('dummy', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('comment', self.gf('django.db.models.fields.CharField')(max_length=250, blank=True)),
            ('import_datetime', self.gf('django.db.models.fields.DateTimeField')(null=True, blank=True)),
            ('test_code', self.gf('django.db.models.fields.related.ForeignKey')(to=orm['lab_clinic_api.TestCode'])),
            ('reference_range_list', self.gf('django.db.models.fields.related.ForeignKey')(to=orm['lab_clinic_reference.ReferenceRangeList'])),
        ))
        db.send_create_signal('lab_clinic_reference', ['ReferenceRangeListItem'])

        # Adding model 'GradingList'
        db.create_table(u'lab_clinic_reference_gradinglist', (
            (u'id', self.gf('django.db.models.fields.AutoField')(primary_key=True)),
            ('created', self.gf('django.db.models.fields.DateTimeField')(default=datetime.datetime.now, blank=True)),
            ('modified', self.gf('django.db.models.fields.DateTimeField')(default=datetime.datetime.now, blank=True)),
            ('user_created', self.gf('django.db.models.fields.CharField')(default='', max_length=250, db_index=True)),
            ('user_modified', self.gf('django.db.models.fields.CharField')(default='', max_length=250, db_index=True)),
            ('hostname_created', self.gf('django.db.models.fields.CharField')(default='mac.local', max_length=50, db_index=True, blank=True)),
            ('hostname_modified', self.gf('django.db.models.fields.CharField')(default='mac.local', max_length=50, db_index=True, blank=True)),
            ('name', self.gf('django.db.models.fields.CharField')(max_length=50)),
            ('description', self.gf('django.db.models.fields.CharField')(max_length=250, null=True, blank=True)),
            ('list_date', self.gf('django.db.models.fields.DateField')(null=True, blank=True)),
        ))
        db.send_create_signal('lab_clinic_reference', ['GradingList'])

        # Adding model 'GradingListItemAudit'
        db.create_table(u'lab_clinic_reference_gradinglistitem_audit', (
            ('created', self.gf('django.db.models.fields.DateTimeField')(default=datetime.datetime.now, blank=True)),
            ('modified', self.gf('django.db.models.fields.DateTimeField')(default=datetime.datetime.now, blank=True)),
            ('user_created', self.gf('django.db.models.fields.CharField')(default='', max_length=250, db_index=True)),
            ('user_modified', self.gf('django.db.models.fields.CharField')(default='', max_length=250, db_index=True)),
            ('hostname_created', self.gf('django.db.models.fields.CharField')(default='mac.local', max_length=50, db_index=True, blank=True)),
            ('hostname_modified', self.gf('django.db.models.fields.CharField')(default='mac.local', max_length=50, db_index=True, blank=True)),
            ('_audit_subject_identifier', self.gf('django.db.models.fields.CharField')(max_length=50, null=True)),
            ('code', self.gf('django.db.models.fields.CharField')(max_length=25, null=True, blank=True)),
            ('scale', self.gf('django.db.models.fields.CharField')(default='increasing', max_length=25)),
            ('gender', self.gf('django.db.models.fields.CharField')(max_length=10)),
            ('hiv_status', self.gf('django.db.models.fields.CharField')(default='ANY', max_length=10)),
            ('value_unit', self.gf('django.db.models.fields.CharField')(max_length=10, null=True)),
            ('value_low', self.gf('django.db.models.fields.DecimalField')(null=True, max_digits=12, decimal_places=4, blank=True)),
            ('value_low_quantifier', self.gf('django.db.models.fields.CharField')(default='>=', max_length=10)),
            ('value_high', self.gf('django.db.models.fields.DecimalField')(null=True, max_digits=12, decimal_places=4, blank=True)),
            ('value_high_quantifier', self.gf('django.db.models.fields.CharField')(default='<=', max_length=10)),
            ('age_low', self.gf('django.db.models.fields.IntegerField')(default=0, null=True, blank=True)),
            ('age_low_unit', self.gf('django.db.models.fields.CharField')(default='D', max_length=10, blank=True)),
            ('age_low_quantifier', self.gf('django.db.models.fields.CharField')(default='>=', max_length=10, blank=True)),
            ('age_high', self.gf('django.db.models.fields.IntegerField')(default=99999, null=True, blank=True)),
            ('age_high_unit', self.gf('django.db.models.fields.CharField')(default='Y', max_length=10, blank=True)),
            ('age_high_quantifier', self.gf('django.db.models.fields.CharField')(default='<=', max_length=10, blank=True)),
            ('panic_value_low', self.gf('django.db.models.fields.DecimalField')(null=True, max_digits=12, decimal_places=4, blank=True)),
            ('panic_value_high', self.gf('django.db.models.fields.DecimalField')(null=True, max_digits=12, decimal_places=4, blank=True)),
            ('active', self.gf('django.db.models.fields.BooleanField')(default=True)),
            ('dummy', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('comment', self.gf('django.db.models.fields.CharField')(max_length=250, blank=True)),
            ('import_datetime', self.gf('django.db.models.fields.DateTimeField')(null=True, blank=True)),
            ('test_code', self.gf('django.db.models.fields.related.ForeignKey')(related_name='_audit_gradinglistitem', to=orm['lab_clinic_api.TestCode'])),
            ('grading_list', self.gf('django.db.models.fields.related.ForeignKey')(related_name='_audit_gradinglistitem', to=orm['lab_clinic_reference.GradingList'])),
            ('grade', self.gf('django.db.models.fields.IntegerField')()),
            ('value_low_calc', self.gf('django.db.models.fields.CharField')(default='ABSOLUTE', max_length=10)),
            ('value_high_calc', self.gf('django.db.models.fields.CharField')(default='ABSOLUTE', max_length=10)),
            ('use_uln', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('use_lln', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('fasting', self.gf('django.db.models.fields.CharField')(default='N/A', max_length=10)),
            ('serum', self.gf('django.db.models.fields.CharField')(default='N/A', max_length=10)),
            ('_audit_timestamp', self.gf('django.db.models.fields.DateTimeField')(auto_now_add=True, db_index=True, blank=True)),
            ('_audit_change_type', self.gf('django.db.models.fields.CharField')(max_length=1)),
            (u'id', self.gf('django.db.models.fields.IntegerField')(db_index=True)),
            ('_audit_id', self.gf('django.db.models.fields.AutoField')(primary_key=True)),
        ))
        db.send_create_signal('lab_clinic_reference', ['GradingListItemAudit'])

        # Adding model 'GradingListItem'
        db.create_table(u'lab_clinic_reference_gradinglistitem', (
            (u'id', self.gf('django.db.models.fields.AutoField')(primary_key=True)),
            ('created', self.gf('django.db.models.fields.DateTimeField')(default=datetime.datetime.now, blank=True)),
            ('modified', self.gf('django.db.models.fields.DateTimeField')(default=datetime.datetime.now, blank=True)),
            ('user_created', self.gf('django.db.models.fields.CharField')(default='', max_length=250, db_index=True)),
            ('user_modified', self.gf('django.db.models.fields.CharField')(default='', max_length=250, db_index=True)),
            ('hostname_created', self.gf('django.db.models.fields.CharField')(default='mac.local', max_length=50, db_index=True, blank=True)),
            ('hostname_modified', self.gf('django.db.models.fields.CharField')(default='mac.local', max_length=50, db_index=True, blank=True)),
            ('code', self.gf('django.db.models.fields.CharField')(max_length=25, null=True, blank=True)),
            ('scale', self.gf('django.db.models.fields.CharField')(default='increasing', max_length=25)),
            ('gender', self.gf('django.db.models.fields.CharField')(max_length=10)),
            ('hiv_status', self.gf('django.db.models.fields.CharField')(default='ANY', max_length=10)),
            ('value_unit', self.gf('django.db.models.fields.CharField')(max_length=10, null=True)),
            ('value_low', self.gf('django.db.models.fields.DecimalField')(null=True, max_digits=12, decimal_places=4, blank=True)),
            ('value_low_quantifier', self.gf('django.db.models.fields.CharField')(default='>=', max_length=10)),
            ('value_high', self.gf('django.db.models.fields.DecimalField')(null=True, max_digits=12, decimal_places=4, blank=True)),
            ('value_high_quantifier', self.gf('django.db.models.fields.CharField')(default='<=', max_length=10)),
            ('age_low', self.gf('django.db.models.fields.IntegerField')(default=0, null=True, blank=True)),
            ('age_low_unit', self.gf('django.db.models.fields.CharField')(default='D', max_length=10, blank=True)),
            ('age_low_quantifier', self.gf('django.db.models.fields.CharField')(default='>=', max_length=10, blank=True)),
            ('age_high', self.gf('django.db.models.fields.IntegerField')(default=99999, null=True, blank=True)),
            ('age_high_unit', self.gf('django.db.models.fields.CharField')(default='Y', max_length=10, blank=True)),
            ('age_high_quantifier', self.gf('django.db.models.fields.CharField')(default='<=', max_length=10, blank=True)),
            ('panic_value_low', self.gf('django.db.models.fields.DecimalField')(null=True, max_digits=12, decimal_places=4, blank=True)),
            ('panic_value_high', self.gf('django.db.models.fields.DecimalField')(null=True, max_digits=12, decimal_places=4, blank=True)),
            ('active', self.gf('django.db.models.fields.BooleanField')(default=True)),
            ('dummy', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('comment', self.gf('django.db.models.fields.CharField')(max_length=250, blank=True)),
            ('import_datetime', self.gf('django.db.models.fields.DateTimeField')(null=True, blank=True)),
            ('test_code', self.gf('django.db.models.fields.related.ForeignKey')(to=orm['lab_clinic_api.TestCode'])),
            ('grading_list', self.gf('django.db.models.fields.related.ForeignKey')(to=orm['lab_clinic_reference.GradingList'])),
            ('grade', self.gf('django.db.models.fields.IntegerField')()),
            ('value_low_calc', self.gf('django.db.models.fields.CharField')(default='ABSOLUTE', max_length=10)),
            ('value_high_calc', self.gf('django.db.models.fields.CharField')(default='ABSOLUTE', max_length=10)),
            ('use_uln', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('use_lln', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('fasting', self.gf('django.db.models.fields.CharField')(default='N/A', max_length=10)),
            ('serum', self.gf('django.db.models.fields.CharField')(default='N/A', max_length=10)),
        ))
        db.send_create_signal('lab_clinic_reference', ['GradingListItem'])


    def backwards(self, orm):
        # Deleting model 'ReferenceRangeList'
        db.delete_table(u'lab_clinic_reference_referencerangelist')

        # Deleting model 'ReferenceRangeListItemAudit'
        db.delete_table(u'lab_clinic_reference_referencerangelistitem_audit')

        # Deleting model 'ReferenceRangeListItem'
        db.delete_table(u'lab_clinic_reference_referencerangelistitem')

        # Deleting model 'GradingList'
        db.delete_table(u'lab_clinic_reference_gradinglist')

        # Deleting model 'GradingListItemAudit'
        db.delete_table(u'lab_clinic_reference_gradinglistitem_audit')

        # Deleting model 'GradingListItem'
        db.delete_table(u'lab_clinic_reference_gradinglistitem')


    models = {
        'lab_clinic_api.testcode': {
            'Meta': {'ordering': "['edc_name']", 'object_name': 'TestCode'},
            'code': ('django.db.models.fields.CharField', [], {'unique': 'True', 'max_length': '15'}),
            'created': ('django.db.models.fields.DateTimeField', [], {'default': 'datetime.datetime.now', 'blank': 'True'}),
            'display_decimal_places': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'edc_code': ('django.db.models.fields.CharField', [], {'max_length': '25', 'null': 'True', 'db_index': 'True'}),
            'edc_name': ('django.db.models.fields.CharField', [], {'max_length': '50', 'null': 'True', 'db_index': 'True'}),
            'formula': ('django.db.models.fields.CharField', [], {'max_length': "'50'", 'null': 'True', 'blank': 'True'}),
            'hostname_created': ('django.db.models.fields.CharField', [], {'default': "'mac.local'", 'max_length': '50', 'db_index': 'True', 'blank': 'True'}),
            'hostname_modified': ('django.db.models.fields.CharField', [], {'default': "'mac.local'", 'max_length': '50', 'db_index': 'True', 'blank': 'True'}),
            u'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'is_absolute': ('django.db.models.fields.CharField', [], {'default': "'absolute'", 'max_length': "'15'"}),
            'modified': ('django.db.models.fields.DateTimeField', [], {'default': 'datetime.datetime.now', 'blank': 'True'}),
            'name': ('django.db.models.fields.CharField', [], {'max_length': '50'}),
            'test_code_group': ('django.db.models.fields.related.ForeignKey', [], {'to': "orm['lab_clinic_api.TestCodeGroup']", 'null': 'True'}),
            'units': ('django.db.models.fields.CharField', [], {'max_length': '25'}),
            'user_created': ('django.db.models.fields.CharField', [], {'default': "''", 'max_length': '250', 'db_index': 'True'}),
            'user_modified': ('django.db.models.fields.CharField', [], {'default': "''", 'max_length': '250', 'db_index': 'True'})
        },
        'lab_clinic_api.testcodegroup': {
            'Meta': {'ordering': "['code']", 'object_name': 'TestCodeGroup'},
            'code': ('django.db.models.fields.CharField', [], {'max_length': '15', 'null': 'True'}),
            'created': ('django.db.models.fields.DateTimeField', [], {'default': 'datetime.datetime.now', 'blank': 'True'}),
            'hostname_created': ('django.db.models.fields.CharField', [], {'default': "'mac.local'", 'max_length': '50', 'db_index': 'True', 'blank': 'True'}),
            'hostname_modified': ('django.db.models.fields.CharField', [], {'default': "'mac.local'", 'max_length': '50', 'db_index': 'True', 'blank': 'True'}),
            u'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'modified': ('django.db.models.fields.DateTimeField', [], {'default': 'datetime.datetime.now', 'blank': 'True'}),
            'name': ('django.db.models.fields.CharField', [], {'max_length': '25', 'null': 'True', 'blank': 'True'}),
            'user_created': ('django.db.models.fields.CharField', [], {'default': "''", 'max_length': '250', 'db_index': 'True'}),
            'user_modified': ('django.db.models.fields.CharField', [], {'default': "''", 'max_length': '250', 'db_index': 'True'})
        },
        'lab_clinic_reference.gradinglist': {
            'Meta': {'ordering': "['name']", 'object_name': 'GradingList'},
            'created': ('django.db.models.fields.DateTimeField', [], {'default': 'datetime.datetime.now', 'blank': 'True'}),
            'description': ('django.db.models.fields.CharField', [], {'max_length': '250', 'null': 'True', 'blank': 'True'}),
            'hostname_created': ('django.db.models.fields.CharField', [], {'default': "'mac.local'", 'max_length': '50', 'db_index': 'True', 'blank': 'True'}),
            'hostname_modified': ('django.db.models.fields.CharField', [], {'default': "'mac.local'", 'max_length': '50', 'db_index': 'True', 'blank': 'True'}),
            u'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'list_date': ('django.db.models.fields.DateField', [], {'null': 'True', 'blank': 'True'}),
            'modified': ('django.db.models.fields.DateTimeField', [], {'default': 'datetime.datetime.now', 'blank': 'True'}),
            'name': ('django.db.models.fields.CharField', [], {'max_length': '50'}),
            'user_created': ('django.db.models.fields.CharField', [], {'default': "''", 'max_length': '250', 'db_index': 'True'}),
            'user_modified': ('django.db.models.fields.CharField', [], {'default': "''", 'max_length': '250', 'db_index': 'True'})
        },
        'lab_clinic_reference.gradinglistitem': {
            'Meta': {'ordering': "['test_code', 'age_low', 'age_low_unit']", 'object_name': 'GradingListItem'},
            'active': ('django.db.models.fields.BooleanField', [], {'default': 'True'}),
            'age_high': ('django.db.models.fields.IntegerField', [], {'default': '99999', 'null': 'True', 'blank': 'True'}),
            'age_high_quantifier': ('django.db.models.fields.CharField', [], {'default': "'<='", 'max_length': '10', 'blank': 'True'}),
            'age_high_unit': ('django.db.models.fields.CharField', [], {'default': "'Y'", 'max_length': '10', 'blank': 'True'}),
            'age_low': ('django.db.models.fields.IntegerField', [], {'default': '0', 'null': 'True', 'blank': 'True'}),
            'age_low_quantifier': ('django.db.models.fields.CharField', [], {'default': "'>='", 'max_length': '10', 'blank': 'True'}),
            'age_low_unit': ('django.db.models.fields.CharField', [], {'default': "'D'", 'max_length': '10', 'blank': 'True'}),
            'code': ('django.db.models.fields.CharField', [], {'max_length': '25', 'null': 'True', 'blank': 'True'}),
            'comment': ('django.db.models.fields.CharField', [], {'max_length': '250', 'blank': 'True'}),
            'created': ('django.db.models.fields.DateTimeField', [], {'default': 'datetime.datetime.now', 'blank': 'True'}),
            'dummy': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'fasting': ('django.db.models.fields.CharField', [], {'default': "'N/A'", 'max_length': '10'}),
            'gender': ('django.db.models.fields.CharField', [], {'max_length': '10'}),
            'grade': ('django.db.models.fields.IntegerField', [], {}),
            'grading_list': ('django.db.models.fields.related.ForeignKey', [], {'to': "orm['lab_clinic_reference.GradingList']"}),
            'hiv_status': ('django.db.models.fields.CharField', [], {'default': "'ANY'", 'max_length': '10'}),
            'hostname_created': ('django.db.models.fields.CharField', [], {'default': "'mac.local'", 'max_length': '50', 'db_index': 'True', 'blank': 'True'}),
            'hostname_modified': ('django.db.models.fields.CharField', [], {'default': "'mac.local'", 'max_length': '50', 'db_index': 'True', 'blank': 'True'}),
            u'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'import_datetime': ('django.db.models.fields.DateTimeField', [], {'null': 'True', 'blank': 'True'}),
            'modified': ('django.db.models.fields.DateTimeField', [], {'default': 'datetime.datetime.now', 'blank': 'True'}),
            'panic_value_high': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '12', 'decimal_places': '4', 'blank': 'True'}),
            'panic_value_low': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '12', 'decimal_places': '4', 'blank': 'True'}),
            'scale': ('django.db.models.fields.CharField', [], {'default': "'increasing'", 'max_length': '25'}),
            'serum': ('django.db.models.fields.CharField', [], {'default': "'N/A'", 'max_length': '10'}),
            'test_code': ('django.db.models.fields.related.ForeignKey', [], {'to': "orm['lab_clinic_api.TestCode']"}),
            'use_lln': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'use_uln': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'user_created': ('django.db.models.fields.CharField', [], {'default': "''", 'max_length': '250', 'db_index': 'True'}),
            'user_modified': ('django.db.models.fields.CharField', [], {'default': "''", 'max_length': '250', 'db_index': 'True'}),
            'value_high': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '12', 'decimal_places': '4', 'blank': 'True'}),
            'value_high_calc': ('django.db.models.fields.CharField', [], {'default': "'ABSOLUTE'", 'max_length': '10'}),
            'value_high_quantifier': ('django.db.models.fields.CharField', [], {'default': "'<='", 'max_length': '10'}),
            'value_low': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '12', 'decimal_places': '4', 'blank': 'True'}),
            'value_low_calc': ('django.db.models.fields.CharField', [], {'default': "'ABSOLUTE'", 'max_length': '10'}),
            'value_low_quantifier': ('django.db.models.fields.CharField', [], {'default': "'>='", 'max_length': '10'}),
            'value_unit': ('django.db.models.fields.CharField', [], {'max_length': '10', 'null': 'True'})
        },
        'lab_clinic_reference.gradinglistitemaudit': {
            'Meta': {'ordering': "['-_audit_timestamp']", 'object_name': 'GradingListItemAudit', 'db_table': "u'lab_clinic_reference_gradinglistitem_audit'"},
            '_audit_change_type': ('django.db.models.fields.CharField', [], {'max_length': '1'}),
            '_audit_id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            '_audit_subject_identifier': ('django.db.models.fields.CharField', [], {'max_length': '50', 'null': 'True'}),
            '_audit_timestamp': ('django.db.models.fields.DateTimeField', [], {'auto_now_add': 'True', 'db_index': 'True', 'blank': 'True'}),
            'active': ('django.db.models.fields.BooleanField', [], {'default': 'True'}),
            'age_high': ('django.db.models.fields.IntegerField', [], {'default': '99999', 'null': 'True', 'blank': 'True'}),
            'age_high_quantifier': ('django.db.models.fields.CharField', [], {'default': "'<='", 'max_length': '10', 'blank': 'True'}),
            'age_high_unit': ('django.db.models.fields.CharField', [], {'default': "'Y'", 'max_length': '10', 'blank': 'True'}),
            'age_low': ('django.db.models.fields.IntegerField', [], {'default': '0', 'null': 'True', 'blank': 'True'}),
            'age_low_quantifier': ('django.db.models.fields.CharField', [], {'default': "'>='", 'max_length': '10', 'blank': 'True'}),
            'age_low_unit': ('django.db.models.fields.CharField', [], {'default': "'D'", 'max_length': '10', 'blank': 'True'}),
            'code': ('django.db.models.fields.CharField', [], {'max_length': '25', 'null': 'True', 'blank': 'True'}),
            'comment': ('django.db.models.fields.CharField', [], {'max_length': '250', 'blank': 'True'}),
            'created': ('django.db.models.fields.DateTimeField', [], {'default': 'datetime.datetime.now', 'blank': 'True'}),
            'dummy': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'fasting': ('django.db.models.fields.CharField', [], {'default': "'N/A'", 'max_length': '10'}),
            'gender': ('django.db.models.fields.CharField', [], {'max_length': '10'}),
            'grade': ('django.db.models.fields.IntegerField', [], {}),
            'grading_list': ('django.db.models.fields.related.ForeignKey', [], {'related_name': "'_audit_gradinglistitem'", 'to': "orm['lab_clinic_reference.GradingList']"}),
            'hiv_status': ('django.db.models.fields.CharField', [], {'default': "'ANY'", 'max_length': '10'}),
            'hostname_created': ('django.db.models.fields.CharField', [], {'default': "'mac.local'", 'max_length': '50', 'db_index': 'True', 'blank': 'True'}),
            'hostname_modified': ('django.db.models.fields.CharField', [], {'default': "'mac.local'", 'max_length': '50', 'db_index': 'True', 'blank': 'True'}),
            u'id': ('django.db.models.fields.IntegerField', [], {'db_index': 'True'}),
            'import_datetime': ('django.db.models.fields.DateTimeField', [], {'null': 'True', 'blank': 'True'}),
            'modified': ('django.db.models.fields.DateTimeField', [], {'default': 'datetime.datetime.now', 'blank': 'True'}),
            'panic_value_high': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '12', 'decimal_places': '4', 'blank': 'True'}),
            'panic_value_low': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '12', 'decimal_places': '4', 'blank': 'True'}),
            'scale': ('django.db.models.fields.CharField', [], {'default': "'increasing'", 'max_length': '25'}),
            'serum': ('django.db.models.fields.CharField', [], {'default': "'N/A'", 'max_length': '10'}),
            'test_code': ('django.db.models.fields.related.ForeignKey', [], {'related_name': "'_audit_gradinglistitem'", 'to': "orm['lab_clinic_api.TestCode']"}),
            'use_lln': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'use_uln': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'user_created': ('django.db.models.fields.CharField', [], {'default': "''", 'max_length': '250', 'db_index': 'True'}),
            'user_modified': ('django.db.models.fields.CharField', [], {'default': "''", 'max_length': '250', 'db_index': 'True'}),
            'value_high': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '12', 'decimal_places': '4', 'blank': 'True'}),
            'value_high_calc': ('django.db.models.fields.CharField', [], {'default': "'ABSOLUTE'", 'max_length': '10'}),
            'value_high_quantifier': ('django.db.models.fields.CharField', [], {'default': "'<='", 'max_length': '10'}),
            'value_low': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '12', 'decimal_places': '4', 'blank': 'True'}),
            'value_low_calc': ('django.db.models.fields.CharField', [], {'default': "'ABSOLUTE'", 'max_length': '10'}),
            'value_low_quantifier': ('django.db.models.fields.CharField', [], {'default': "'>='", 'max_length': '10'}),
            'value_unit': ('django.db.models.fields.CharField', [], {'max_length': '10', 'null': 'True'})
        },
        'lab_clinic_reference.referencerangelist': {
            'Meta': {'ordering': "['name']", 'object_name': 'ReferenceRangeList'},
            'created': ('django.db.models.fields.DateTimeField', [], {'default': 'datetime.datetime.now', 'blank': 'True'}),
            'description': ('django.db.models.fields.CharField', [], {'max_length': '250', 'null': 'True', 'blank': 'True'}),
            'hostname_created': ('django.db.models.fields.CharField', [], {'default': "'mac.local'", 'max_length': '50', 'db_index': 'True', 'blank': 'True'}),
            'hostname_modified': ('django.db.models.fields.CharField', [], {'default': "'mac.local'", 'max_length': '50', 'db_index': 'True', 'blank': 'True'}),
            u'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'list_date': ('django.db.models.fields.DateField', [], {'null': 'True', 'blank': 'True'}),
            'modified': ('django.db.models.fields.DateTimeField', [], {'default': 'datetime.datetime.now', 'blank': 'True'}),
            'name': ('django.db.models.fields.CharField', [], {'max_length': '50'}),
            'user_created': ('django.db.models.fields.CharField', [], {'default': "''", 'max_length': '250', 'db_index': 'True'}),
            'user_modified': ('django.db.models.fields.CharField', [], {'default': "''", 'max_length': '250', 'db_index': 'True'})
        },
        'lab_clinic_reference.referencerangelistitem': {
            'Meta': {'ordering': "['test_code', 'age_low', 'age_low_unit']", 'object_name': 'ReferenceRangeListItem'},
            'active': ('django.db.models.fields.BooleanField', [], {'default': 'True'}),
            'age_high': ('django.db.models.fields.IntegerField', [], {'default': '99999', 'null': 'True', 'blank': 'True'}),
            'age_high_quantifier': ('django.db.models.fields.CharField', [], {'default': "'<='", 'max_length': '10', 'blank': 'True'}),
            'age_high_unit': ('django.db.models.fields.CharField', [], {'default': "'Y'", 'max_length': '10', 'blank': 'True'}),
            'age_low': ('django.db.models.fields.IntegerField', [], {'default': '0', 'null': 'True', 'blank': 'True'}),
            'age_low_quantifier': ('django.db.models.fields.CharField', [], {'default': "'>='", 'max_length': '10', 'blank': 'True'}),
            'age_low_unit': ('django.db.models.fields.CharField', [], {'default': "'D'", 'max_length': '10', 'blank': 'True'}),
            'code': ('django.db.models.fields.CharField', [], {'max_length': '25', 'null': 'True', 'blank': 'True'}),
            'comment': ('django.db.models.fields.CharField', [], {'max_length': '250', 'blank': 'True'}),
            'created': ('django.db.models.fields.DateTimeField', [], {'default': 'datetime.datetime.now', 'blank': 'True'}),
            'dummy': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'gender': ('django.db.models.fields.CharField', [], {'max_length': '10'}),
            'hiv_status': ('django.db.models.fields.CharField', [], {'default': "'ANY'", 'max_length': '10'}),
            'hostname_created': ('django.db.models.fields.CharField', [], {'default': "'mac.local'", 'max_length': '50', 'db_index': 'True', 'blank': 'True'}),
            'hostname_modified': ('django.db.models.fields.CharField', [], {'default': "'mac.local'", 'max_length': '50', 'db_index': 'True', 'blank': 'True'}),
            u'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'import_datetime': ('django.db.models.fields.DateTimeField', [], {'null': 'True', 'blank': 'True'}),
            'modified': ('django.db.models.fields.DateTimeField', [], {'default': 'datetime.datetime.now', 'blank': 'True'}),
            'panic_value_high': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '12', 'decimal_places': '4', 'blank': 'True'}),
            'panic_value_low': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '12', 'decimal_places': '4', 'blank': 'True'}),
            'reference_range_list': ('django.db.models.fields.related.ForeignKey', [], {'to': "orm['lab_clinic_reference.ReferenceRangeList']"}),
            'scale': ('django.db.models.fields.CharField', [], {'default': "'increasing'", 'max_length': '25'}),
            'test_code': ('django.db.models.fields.related.ForeignKey', [], {'to': "orm['lab_clinic_api.TestCode']"}),
            'user_created': ('django.db.models.fields.CharField', [], {'default': "''", 'max_length': '250', 'db_index': 'True'}),
            'user_modified': ('django.db.models.fields.CharField', [], {'default': "''", 'max_length': '250', 'db_index': 'True'}),
            'value_high': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '12', 'decimal_places': '4', 'blank': 'True'}),
            'value_high_quantifier': ('django.db.models.fields.CharField', [], {'default': "'<='", 'max_length': '10'}),
            'value_low': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '12', 'decimal_places': '4', 'blank': 'True'}),
            'value_low_quantifier': ('django.db.models.fields.CharField', [], {'default': "'>='", 'max_length': '10'}),
            'value_unit': ('django.db.models.fields.CharField', [], {'max_length': '10', 'null': 'True'})
        },
        'lab_clinic_reference.referencerangelistitemaudit': {
            'Meta': {'ordering': "['-_audit_timestamp']", 'object_name': 'ReferenceRangeListItemAudit', 'db_table': "u'lab_clinic_reference_referencerangelistitem_audit'"},
            '_audit_change_type': ('django.db.models.fields.CharField', [], {'max_length': '1'}),
            '_audit_id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            '_audit_subject_identifier': ('django.db.models.fields.CharField', [], {'max_length': '50', 'null': 'True'}),
            '_audit_timestamp': ('django.db.models.fields.DateTimeField', [], {'auto_now_add': 'True', 'db_index': 'True', 'blank': 'True'}),
            'active': ('django.db.models.fields.BooleanField', [], {'default': 'True'}),
            'age_high': ('django.db.models.fields.IntegerField', [], {'default': '99999', 'null': 'True', 'blank': 'True'}),
            'age_high_quantifier': ('django.db.models.fields.CharField', [], {'default': "'<='", 'max_length': '10', 'blank': 'True'}),
            'age_high_unit': ('django.db.models.fields.CharField', [], {'default': "'Y'", 'max_length': '10', 'blank': 'True'}),
            'age_low': ('django.db.models.fields.IntegerField', [], {'default': '0', 'null': 'True', 'blank': 'True'}),
            'age_low_quantifier': ('django.db.models.fields.CharField', [], {'default': "'>='", 'max_length': '10', 'blank': 'True'}),
            'age_low_unit': ('django.db.models.fields.CharField', [], {'default': "'D'", 'max_length': '10', 'blank': 'True'}),
            'code': ('django.db.models.fields.CharField', [], {'max_length': '25', 'null': 'True', 'blank': 'True'}),
            'comment': ('django.db.models.fields.CharField', [], {'max_length': '250', 'blank': 'True'}),
            'created': ('django.db.models.fields.DateTimeField', [], {'default': 'datetime.datetime.now', 'blank': 'True'}),
            'dummy': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'gender': ('django.db.models.fields.CharField', [], {'max_length': '10'}),
            'hiv_status': ('django.db.models.fields.CharField', [], {'default': "'ANY'", 'max_length': '10'}),
            'hostname_created': ('django.db.models.fields.CharField', [], {'default': "'mac.local'", 'max_length': '50', 'db_index': 'True', 'blank': 'True'}),
            'hostname_modified': ('django.db.models.fields.CharField', [], {'default': "'mac.local'", 'max_length': '50', 'db_index': 'True', 'blank': 'True'}),
            u'id': ('django.db.models.fields.IntegerField', [], {'db_index': 'True'}),
            'import_datetime': ('django.db.models.fields.DateTimeField', [], {'null': 'True', 'blank': 'True'}),
            'modified': ('django.db.models.fields.DateTimeField', [], {'default': 'datetime.datetime.now', 'blank': 'True'}),
            'panic_value_high': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '12', 'decimal_places': '4', 'blank': 'True'}),
            'panic_value_low': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '12', 'decimal_places': '4', 'blank': 'True'}),
            'reference_range_list': ('django.db.models.fields.related.ForeignKey', [], {'related_name': "'_audit_referencerangelistitem'", 'to': "orm['lab_clinic_reference.ReferenceRangeList']"}),
            'scale': ('django.db.models.fields.CharField', [], {'default': "'increasing'", 'max_length': '25'}),
            'test_code': ('django.db.models.fields.related.ForeignKey', [], {'related_name': "'_audit_referencerangelistitem'", 'to': "orm['lab_clinic_api.TestCode']"}),
            'user_created': ('django.db.models.fields.CharField', [], {'default': "''", 'max_length': '250', 'db_index': 'True'}),
            'user_modified': ('django.db.models.fields.CharField', [], {'default': "''", 'max_length': '250', 'db_index': 'True'}),
            'value_high': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '12', 'decimal_places': '4', 'blank': 'True'}),
            'value_high_quantifier': ('django.db.models.fields.CharField', [], {'default': "'<='", 'max_length': '10'}),
            'value_low': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '12', 'decimal_places': '4', 'blank': 'True'}),
            'value_low_quantifier': ('django.db.models.fields.CharField', [], {'default': "'>='", 'max_length': '10'}),
            'value_unit': ('django.db.models.fields.CharField', [], {'max_length': '10', 'null': 'True'})
        }
    }

    complete_apps = ['lab_clinic_reference']